### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by mwinokan** [GRIFFINCollaboration/NTuple2EventTree#15]
Hi there,

I'm having issues when setting up NTuple2EventTree. Following what I think is the correct building and compilation procedure I'm getting issues with linking the CommandLineInterface libraries.

Here is my procedure starting from scratch with installing GRSISort:

(I have ROOT 6.08/02 installed with the required and optional packages, confirmed by running `root-config --features`)
```

cd

echo "source /opt/root/bin/thisroot.sh" >> ~/.bash_profile 
source ~/.bash_profile

git clone https://github.com/GRIFFINCollaboration/GRSISort.git

cd GRSISort

echo "source ~/GRSISort/thisgrsi.sh" >> ~/.bash_profile 
source ~/.bash_profile

make clean
make -j 3

cd

git clone https://github.com/GRIFFINCollaboration/CommandLineInterface

cd CommandLineInterface

make clean
make

cd

git clone https://github.com/GRIFFINCollaboration/NTuple2EventTree

cd NTuple2EventTree

make clean
make
```

All the compilations above complete without errors but then attempting to run `./NTuple2EventTree` in its directory produces the following error:

`./NTuple2EventTree: error while loading shared libraries: libCommandLineInterface.so: cannot open shared object file: No such file or directory`

Any help is appreciated,

Max

**Comment by r3dunlop** [comment]
Nowhere did you tell NTuple2EventTree where libCommandLineInterface.so lived. Try adding the directory where libCommandLineInterface.so is to your LD_LIBRARY_PATH in your bash_profile.

**Comment by mwinokan** [comment]
Thank you.

Adding the following lines to my .bash_profile has fixed the issue:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/CommandLineInterface
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
```
