### ISSUE TITLE
GRSISort v4.0.0.1 Compatibility

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple2EventTree#17]
When compiling against GRSISort v4.0.0.1 I get the error: 
```
In file included from Converter.cc:1:0:
Converter.hh:12:10: fatal error: TGRSIRunInfo.h: No such file or directory
 #include "TGRSIRunInfo.h"
          ^~~~~~~~~~~~~~~~
```
after running the `make` command. Any suggestions?

**Comment by cnatzke** [comment]
I compiled against  GRSISort v3.1.3.5 and I did not get this issue. Did the TGRSIRunInfo library change or get removed in v4.0.0.1? 

I searched through the GRSISort v4.0.0.1 install and did not find it.

**Comment by cnatzke** [comment]
Fixed that error. To compile against v4.0.0.1 you have to change 
```
#include TGRSIRunInfo.h
```
to 
```
#include TRunInfo.h
```
in  `Converter.hh`

Ntuple2EventTree does not compile with this simple fix. The next error I get is 
```
Converter.hh:15:10: fatal error: TGriffin.h: No such file or directory
 #include "TGriffin.h"
          ^~~~~~~~~~~~
```
and I found `TGriffin.h` in the GRSIData/include directory, but do not know how to point the Makefile to it. I added the line 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/cnatzke/Programs/GRSISort/GRSIData/include
```
to my bashrc but it did not help.

**Comment by r3dunlop** [comment]
Did you change the grsi envy variables properly? I think it’s detailed in the installation on the wiki or on the readme.

**Comment by cnatzke** [comment]
I have 
```
GRSI.ParserLibrary: $(GRSISYS)/GRSIData/lib/libGRSIData.so
```
at the end of my `.grsirc`. Is that what you mean?

**Comment by VinzenzBildstein** [comment]
Try adding a ```-I$(GRSISYS)/GRSIData/include``` to the flags in the makefile, that should fix this.

And if this does fix it please push your changes.

**Comment by cnatzke** [comment]
That fixed the library issue, but there is a new one: 
```shell
Converter.hh:32:29: error: ‘TMnemonic::EDigitizer’ has not been declared
         int  Cfd(TMnemonic::EDigitizer);
                             ^~~~~~~~~~
Converter.cc:122:31: error: ‘int Converter::Cfd’ is not a static data member of ‘class Converter’
 int Converter::Cfd(TMnemonic::EDigitizer digitizer)
                               ^~~~~~~~~~
Converter.cc:122:31: error: ‘EDigitizer’ is not a member of ‘TMnemonic’
Converter.cc: In member function ‘bool Converter::Run()’:
```

I tried adding `#include TMnemonic.h` to both `Converter.hh` and `Converter.cc` but that did not help.

**Comment by VinzenzBildstein** [comment]
No, the EDigitizer is now part of the detector library. So you will need to access is just as EDigitizer I think? And include TGRSIMnemonic.h in Converter.hh.

**Comment by VinzenzBildstein** [comment]
I'm assuming this has been solved by now
