### ISSUE TITLE
Out of Range Error in Sorting 

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple2EventTree#18]

**Comment by cnatzke** [comment]
When sorting a basic 60Co simulation output file via 
```
../NTuple2EventTree -sf ../Settings.dat -if Co60.root -vl 2
```
the program throws an `std::out_of_range` error at a specific fragment. I suspect this is from a mismatch between crystal/detector numbering schemes but am unsure of where. I have attached a snippet of the output:
```
will read from 1 files
created new fragment 0x55d3d5aa4270
Initialized values of fragment at address 62 = 0x3e
DaqTimeStamp: Nov 06 23:00:16
DaqId      0
        TriggerId[0]
FragmentId:   0
TriggerBit:  0x00000000
NetworkPacketNumber: 0
Channel: 0      Name: GRG15RN00A
        Channel Num:      0
        Channel Address: 0x0000003e
        Charge:          0x000001c1
        CFD:             0x00000000
        ZC:              0x00000000
        TimeStamp:       12150001612131426
Does Not have a wave form stored.
Initialized values of fragment at address 63 = 0x3f
DaqTimeStamp: Nov 06 23:00:16
DaqId      1
        TriggerId[0]
FragmentId:   0
TriggerBit:  0x00000000
NetworkPacketNumber: 0
Channel: 0      Name: GRG15WN00A
        Channel Num:      0
        Channel Address: 0x0000003f
        Charge:          0x00000226
        CFD:             0x00000000
        ZC:              0x00000000
        TimeStamp:       12150001612131426
Does Not have a wave form stored.
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 16) >= this->size() (which is 16)
Aborted (core dumped)
```

**Comment by cnatzke** [comment]
Investigating further, the simulation numbers the detectors as 1-16 whereas NTuple2EventTree expects 0-15. The same mismatch is present for the crystals (1-4 vs 0-3).

**Comment by cnatzke** [comment]
Update: 
The line that causes the error is 
``` 
 smearedEnergy = Random.Gaus(fDepEnergy,fSettings->Resolution(fSystemID,fDetNumber,fCryNumber,fDepEnergy));
``` 
around line 200 of `Converter.cc`. The issue is one of the BGO hits is labeled as detector 16 where the array is [0,15].  I think this is related to how the simulation handles BGO's; see the related issue in the simulation in the simulation repository [here](https://github.com/GRIFFINCollaboration/detectorSimulations_v10/issues/65). I could expand the array size to be [0,16] but I do not know if that creates further issues. Thoughts?

**Comment by VinzenzBildstein** [comment]
We need to figure out how we number detectors in the simulation. In GRSISort we go directly from the mnemonics, meaning detectors are number starting with 1. If the simulation also does this (and it seems to be doing that for GRIFFIN?), we just need to update the converter to use <detector number - 1> as an index.
If the simulation starts counting at 1 for some detectors and at 0 for others, we should unify that. I would lean to count from 1 in the simulation (easier match to the mnemonics), but if that is too difficult for some detector classes, we could also count from 0.

**Comment by cnatzke** [comment]
The simulation was labeled from [1,16], but we changed it to [0,15] for this issue: 
[Here](https://github.com/GRIFFINCollaboration/detectorSimulations_v10/issues/59)

**Comment by VinzenzBildstein** [comment]
That was for the GRIFFIN detectors though, not the BGOs, right?

**Comment by VinzenzBildstein** [comment]
As far as I can see it we have two options:
a) have the simulation create detector numbers from 1-16, and convert those to 0-15 in the Settings class of NTuple2EventTree (either with the settings file running from 1-16 as well, or 0-15)
b) have the simulation create detector numbers from 0-15 and then assign mnemonics labeled 1-16 to them

Even though a) is more work I think I would prefer that solution as it makes things a bit more consistent.

**Comment by cnatzke** [comment]
I agree. I think we should go with option a).
