### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by mrocchini** [GRIFFINCollaboration/NTuple2EventTree#19]
HOSTNAME     = nessa.physics.uoguelph.ca
SYSTEM       = Linux
OS           = CentOS
VER          = 6.10
GRSISYS      = /helioshome/mrocchin/Work/software/GRSISort
ROOTSYS      = /opt/cern/root/root6
ROOT Version = 6.08/06

Computer and Path to File that failed:

GRSISort Branch = master

commit d49cb662c3841f22b5d8e069e7aceb3ade0b5ff2
Merge: 26b30f9 16f9201
Author: Vinzenz Bildstein <vbildste@uoguelph.ca>
Date:   Thu May 7 12:01:39 2020 -0400

    Merge pull request #1158 from VinzenzBildstein/master

    Fixed issue with cross talk correction in grsiproof

I'm getting a fatal error when I try to install NTuple2EventTree. I changed the paths in the Makefile as requested, but then when I do make:
```
[mrocchin@nessa NTuple2EventTree]$ make clean
[mrocchin@nessa NTuple2EventTree]$ make
rm -f NTuple2EventTreeDictionary.cc NTuple2EventTreeDictionary.h; rootcint -f NTuple2EventTreeDictionary.cc -c -I/opt/cern/root/root6/include -I/helioshome/mrocchin/Work/software/GriffinSimulations/CommandLineInterface -I. -fPIC RootLinkDef.h
g++ -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/helioshome/mrocchin/Work/software/GRSISort/include -I/opt/cern/root/root6/include -I/helioshome/mrocchin/Work/software/GriffinSimulations/CommandLineInterface -I. -fPIC -c NTuple2EventTreeDictionary.cc
g++ Converter.cc -c -I/opt/cern/root/root6/include -I/helioshome/mrocchin/Work/software/GriffinSimulations/CommandLineInterface -I. -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/helioshome/mrocchin/Work/software/GRSISort/include -o Converter.o
In file included from Converter.cc:1:0:
Converter.hh:12:26: fatal error: TGRSIRunInfo.h: No such file or directory
 #include "TGRSIRunInfo.h"
                          ^
compilation terminated.
make: *** [Converter.o] Error 1
[mrocchin@nessa NTuple2EventTree]$
```
It's interesting because when I installed NTuple, instead, everything was running smooth. And also there I changed the paths as requested (I checked, the paths in my Makefiles of NTuple and NTuple2EventTree are the same).
I'm using grsisort version 4.0.0.2.

**Comment by VinzenzBildstein** [comment]
First of NTuple does not depend on GRSISort at all, so it's not surprising you don't get any error like this with NTuple.

I'll have to look into the makefile and see how we try to compile NTuple2EventTree and whether this has been updated for GRSISort v4 ... Essentially the error come from the fact that $GRSISYS/include is listed as a directory for header files, but that directory only contains TRunInfo.h. TGRSIRunInfo.h is nowadays in $GRSISYS/GRSIData/include. You could add that by hand to your makefile, but let me check if that is correct or if NTuple2EventTree should actually be using TRunInfo instead of TGRSIRunInfo.

**Comment by VinzenzBildstein** [comment]
Hmm, so in my Makefile line 49 reads
```
CXXFLAGS    = -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 $(shell $(GRSI_CONFIG) --cflags) -I$(GRSISYS)/GRSIData/include
```
Could it be that you're using an old version of NTuple2EventTree?

**Comment by VinzenzBildstein** [comment]
Ah, sorry, I see what happened now. These changes are changes I made in the descant branch and haven't merged back into the master branch. I'll do that now.

**Comment by mrocchini** [comment]
Ok, thank you also for the explanations! As soon as you merge I pull and try. I'll let you know if it is working.

**Comment by VinzenzBildstein** [comment]
Okay, PR #20 & #21 should fix this. Let me know if this works.

**Comment by mrocchini** [comment]
Hi Vinzenz, is working perfectly. I also proofed the simulations with my selector, no error and I see the cascade that I was simulating in coincidence.
I'll now check if the angular correlations are there but for the moment I would say that this issue can be closed.
Thank a lot again!
