### ISSUE TITLE
Runtime error "cannot dynamically load position-independent executable"

### ISSUE THREAD

**Issue by cnatzke** [GRIFFINCollaboration/NTuple2EventTree#25]
GRSISort Version: 4.0.0.3
ROOT Version: 6.24/06
OS: Ubuntu 20.04.4 LTS

When I run ```NTuple2EventTree``` on a GRIFFIN simulation output file I get the following warning:

```
Error in <TCling::RegisterModule>: Cannot open shared library /home/cnatzke/griffin-collaboration/NTuple2EventTree/NTuple2EventTree for dictionary NTuple2EventTreeDictionary:
  /home/cnatzke/griffin-collaboration/NTuple2EventTree/NTuple2EventTree: cannot dynamically load position-independent executable
will read from 1 files
created new fragment 0x5632910b4980
TMnemonic: No data library set, some things like timing won't work!
```

I am not sure what this means. I get an output analysis tree but I'm not sure if it converted properly. Any thoughts?

Also the line 
```
TMnemonic: No data library set, some things like timing won't work!
``` 
makes me think I'm missing some configuration option but I'm not sure what.

**Comment by cnatzke** [comment]
I get the same error after a clean compile. I think I have a version mismatch in the C compiler based on these warnings after the ```make``` command: 
```
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20200808'
  Extraction of runtime standard library version was: '20210601'
Warning: Unused class rule: vector<Detector>
Warning: Unused class rule: Detector
```

**Comment by VinzenzBildstein** [comment]
That warning is fairly common on Ubuntu machines if you have the automatic updates enabled. Ubuntu updates gcc fairly often and thus it now mismatches the gcc that was installed when you compiled your root version. 

I'm not sure where the error is coming from. Sounds like something has maybe changed in the way root dictionaries work, but I'm not sure.

**Comment by cnatzke** [comment]
I just installed root v6.26.04 to see if it makes a difference. 

Here are the commands I used
```
wget https://root.cern/download/root_v6.26.04.Linux-ubuntu20-x86_64-gcc9.4.tar.gz
tar xvfz root_v6.26.04.Linux-ubuntu20-x86_64-gcc9.4.tar.gz
source root/bin/thisroot.sh
```

**Comment by VinzenzBildstein** [comment]
So that root version was built with gcc 9.4. What version do you have installed (```gcc --version```)?

**Comment by cnatzke** [comment]
```
--> gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by VinzenzBildstein** [comment]
Huh. No idea where that warning comes from then. 
Is it still the same versions that it's reporting, i.e.
```
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20200808'
  Extraction of runtime standard library version was: '20210601'
```?

**Comment by cnatzke** [comment]
Using the newly installed root v6.26.04 I recompiled _GRSISort_, _CommandLineInterface_, and _NTuple2EventTree_ and no longer got the library mismatch error. 

I did change the CommandLineInterface ```CMakeLists.txt``` from 
```
# specify the C++ standard
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED True)

string(APPEND CMAKE_CXX_FLAGS " -pedantic -Wall -Wno-long-long -g -O3")
```
to 
```
# specify the C++ standard
# set(CMAKE_CXX_STANDARD 14)
# set(CMAKE_CXX_STANDARD_REQUIRED True)

string(APPEND CMAKE_CXX_FLAGS "${ROOT_CXX_FLAGS} -pedantic -Wall -Wno-long-long -g -O3")
```
so it picks up whatever cxx standard ROOT is using.

The only concerning lines in compilation of _NTuple2EventTree_ is now 
```
Warning: Unused class rule: vector<Detector>
Warning: Unused class rule: Detector
```
and I still get the same error when trying to run _NTuple2EventTree_

```
--> ./NTuple2EventTree
Warning in <UnknownClass::SetDisplay>: DISPLAY not set, setting it to tmux(630782).%8:0.0
Error in <TCling::RegisterModule>: Cannot open shared library /home/cnatzke/programs/griffin-collaboration/NTuple2EventTree/NTuple2EventTree for dictionary NTuple2EventTreeDictionary:
  /home/cnatzke/programs/griffin-collaboration/NTuple2EventTree/NTuple2EventTree: cannot dynamically load position-independent executable
use ./NTuple2EventTree with following flags:
        [-sf <std::string             >: settings file (required)]
        [-if <std::vector<std::string>>: input file(s) (required)]
        [-rn <int                     >: run number (default = 0)]
        [-sn <int                     >: sub-run number (default = 0)]
        [-ri <std::string             >: run info file (default = '')]
        [-vl <int                     >: verbosity level (default = 0)]
        [-wf                           : write FragmentTree to separate file]
Missing input file name(s)!
```

**Comment by VinzenzBildstein** [comment]
The unused class rule warning is "normal", this also shows up in other instances (like compiling grsisort I think?).

Still don't know what the error means, it's like it's trying to use the executable as a library? Can you try using ldd on the executable and see what that prints out?

**Comment by cnatzke** [comment]
I think so. I get an output analysis tree but I've yet to check if all the simulated events make it through the conversion.

**Comment by cnatzke** [comment]
I still get the "cannot dynamically load position-independent executable" error but the simulation output file is converted into an analysis tree. 

As far as I can tell this error is acting more as a warning.

**Comment by cnatzke** [comment]
I took another look at this issue and I don't think the analysis trees are being generated properly. The detector IDs get placed in the 62,000 range and the energies are incorrect. The simulation output files are correct so I suspect something is going on in the conversion stage. 

I have been using `Ntuple2EventTree` in a Docker container based Ubuntu 20.04 and I suspected Docker might be causing this issue. To investigate I built the whole software stack in a clean virtual machine of Ubuntu 20.04 using the following versions:

- ROOT v6.26.10
- GRSISort v4.0.0.3
- GRSIData v0.1.1.2
- Fresh pull of Ntuple2EventTree
- Fresh pull of CommandLineInterface

and I still get the same error: 
```
Error in <TCling::RegisterModule>: Cannot open shared library /home/cnatzke/griffin-collaboration/NTuple2EventTree/NTuple2EventTree for dictionary NTuple2EventTreeDictionary:
  /home/cnatzke/griffin-collaboration/NTuple2EventTree/NTuple2EventTree: cannot dynamically load position-independent executable
```
I can share the virtual machine so you can take a look if you're interested. I built it to be portable.

**Comment by cnatzke** [comment]
I also build the whole stack using (same versions) in a Centos-Stream-8 box and did not get the error. This makes me think it's a Ubuntu issue but I don't know how to diagnose that.

**Comment by cnatzke** [comment]
For example this is the `GetArrayNumber` call from the processed analysis tree:
![Screenshot 2023-05-05 at 2 01 42 PM](https://user-images.githubusercontent.com/17180596/236533924-303621fa-fec6-4ffe-8529-07aa67f6c856.png)

**Comment by VinzenzBildstein** [comment]
65528 is 0xfff8, which makes it look like it's some kind of default value. I'm wondering about the warning ```cannot dynamically load position-independent executable```. This could be related to loading a specific library after the program has been started (which is something we do in grsisort to load the experiment specific library, e.g. libGRSIData.so). If we do the same thing in NTuple2EventTree (which is very likely) and that doesn't work, then the program won't be able to assign some things I guess. 
The thing is that this loading of libraries works on a normal ubuntu installation. Could this be a bug/feature from docker?

**Comment by cnatzke** [comment]
I've tried in both in `Docker` and `Vagrant` on clean installs. It seems odd to me that in both cases `grsisort` works but `NTuple2EventTree` doesn't. 

It didn't happen on a Centos Vagrant machine so I don't think its the virtualisation, but I'm not sure how to check.

**Comment by cnatzke** [comment]
I started looking into the output of `strace` but I don't really know where the issue would show up:
[Uploading strace_ntuple.txt…]()

**Comment by VinzenzBildstein** [comment]
> For example this is the `GetArrayNumber` call from the processed analysis tree:
> ![Screenshot 2023-05-05 at 2 01 42 PM](https://user-images.githubusercontent.com/17180596/236533924-303621fa-fec6-4ffe-8529-07aa67f6c856.png)

This plot uses the GetArrayNumber function of TDetectorHit, which simply returns GetDetector, which in turn gets the channel of the hit (based on the calibrations used), and returns TChannel::GetDetectorNumber, which is the detector part of the mnemonic of that channel. 

To see what goes wrong here, you could check the analysis tree to see what addresses are in it, and what the corresponding channels for those addresses are set to. You can either do this by scanning the analysis tree ```AnalysisTree->Scan("fAddress:fAddress","","col=#x")```, and then check a few of the results using ```TChannel::GetChannel(<address>)->Print()``` and see if the detector number is set correctly in those channels.

**Comment by cnatzke** [comment]
GRSISort segfaults after the call
```
TChannel::GetChannel(<address>)->Print()
```

e.g. 
```
GRSI [1] AnalysisTree->Scan("fAddress:fAddress","","col=#x")
***********************************************
*    Row   * Instance *  fAddress *  fAddress *
***********************************************
*        0 *        0 *      0x2f *        47 *
*        1 *        0 *           *           *
*        2 *        0 *           *           *
*        3 *        0 *      0x23 *        35 *
*        4 *        0 *      0x3b *        59 *
*        5 *        0 *      0x3f *        63 *
*        6 *        0 *      0x30 *        48 *
*        7 *        0 *           *           *
*        8 *        0 *      0x30 *        48 *
*        9 *        0 *       0x5 *         5 *
*        9 *        1 *      0x2d *        45 *
*       10 *        0 *           *           *
*       11 *        0 *      0x17 *        23 *
*       12 *        0 *       0x5 *         5 *
*       13 *        0 *      0x2a *        42 *
*       14 *        0 *           *           *
*       15 *        0 *      0x2a *        42 *
*       16 *        0 *           *           *
*       17 *        0 *      0x16 *        22 *
*       17 *        1 *      0x20 *        32 *
*       18 *        0 *       0x1 *         1 *
*       18 *        1 *       0x3 *         3 *
*       18 *        2 *      0x3a *        58 *
*       19 *        0 *           *           *
*       20 *        0 *         0 *         0 *
Type <CR> to continue or q to quit ==> q
***********************************************
```
```
GRSI [8] TChannel::GetChannel(0x3)->Print()

 *** Break *** segmentation violation
 Generating stack trace...
 0x00007f82553833b5 in <unknown> from /home/vagrant/cern/root/lib/libCling.so
 0x00007f8255386305 in <unknown> from /home/vagrant/cern/root/lib/libCling.so
 0x00007f8255386754 in <unknown> from /home/vagrant/cern/root/lib/libCling.so
 0x00007f82554735a7 in <unknown> from /home/vagrant/cern/root/lib/libCling.so
 0x00007f8255277f4c in <unknown> from /home/vagrant/cern/root/lib/libCling.so
 0x00007f825528f7b2 in TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) + 0xe02 from /home/vagrant/cern/root/lib/libCling.so
 0x00007f825e4185dc in TApplication::ProcessLine(char const*, bool, int*) + 0xb4c from /home/vagrant/cern/root/lib/libCore.so.6.26
 0x00007f825ee28029 in TGRSIint::ProcessLine(char const*, bool, int*) at /home/vagrant/GRSISort/libraries/TGRSIint/TGRSIint.cxx:265 from /home/vagrant/GRSISort/lib/libTGRSIint.so
 0x00007f825d2023c9 in TRint::ProcessLineNr(char const*, char const*, int*) + 0x159 from /home/vagrant/cern/root/lib/libRint.so.6.26
 0x00007f825d2027da in TRint::HandleTermInput() + 0x24a from /home/vagrant/cern/root/lib/libRint.so.6.26
 0x00007f825e56ced2 in TUnixSystem::CheckDescriptors() + 0xd2 from /home/vagrant/cern/root/lib/libCore.so.6.26
 0x00007f825e56ed18 in TUnixSystem::DispatchOneEvent(bool) + 0x5b8 from /home/vagrant/cern/root/lib/libCore.so.6.26
 0x00007f825e47dd89 in TSystem::Run() + 0xe9 from /home/vagrant/cern/root/lib/libCore.so.6.26
 0x00007f825e415426 in TApplication::Run(bool) + 0x26 from /home/vagrant/cern/root/lib/libCore.so.6.26
 0x00007f825d20432e in TRint::Run(bool) + 0x4ce from /home/vagrant/cern/root/lib/libRint.so.6.26
 0x00005644b39118b1 in main + 0xb1 from grsisort
 0x00007f825b88f083 in __libc_start_main + 0xf3 from /lib/x86_64-linux-gnu/libc.so.6
 0x00005644b3911c0e in _start + 0x2e from grsisort
 ```

**Comment by cnatzke** [comment]
I found the block in ROOT that throws the error.
```
// If this call happens after dlopen has finished (i.e. late registration)
   // there is no need to dlopen the library recursively. See ROOT-8437 where
   // the dyLibName would correspond to the binary.
   if (!lateRegistration) {
 
      if (isSharedLib) {
         // We need to open the dictionary shared library, to resolve symbols
         // requested by the JIT from it: as the library is currently being dlopen'ed,
         // its symbols are not yet reachable from the process.
         // Recursive dlopen seems to work just fine.
         void* dyLibHandle = dlopen(dyLibName.c_str(), RTLD_LAZY | RTLD_GLOBAL);
         if (dyLibHandle) {
            [fRegisterModuleDyLibs](https://root.cern.ch/doc/master/classTCling.html#a0a17b0ffbb5e6a68220e41a5bea45581).push_back(dyLibHandle);
            wasDlopened = true;
         } else {
            [PrintDlError](https://root.cern.ch/doc/master/TCling_8cxx.html#adc4fa50045094ff374119467c33b0fdb)(dyLibName.c_str(), modulename);
         }
      }
   } // if (!lateRegistration)
```

I'm not sure if it's helpful.

**Comment by VinzenzBildstein** [comment]
What happens when you just use ```TChannel::GetChannel(0x3)``` after opening the analysis file? Does this return a null pointer? In that case what is the result of ```TChannel::WriteCalFile()```?

**Comment by cnatzke** [comment]
>What happens when you just use TChannel::GetChannel(0x3) after opening the analysis file?

I get a null pointer.

>In that case what is the result of TChannel::WriteCalFile()?

Nothing, no output to terminal.

**Comment by VinzenzBildstein** [comment]
Okay, that means that there is no calibration saved in the analysis file. Either something is going wrong in NTuple2EventTree so it doesn't get written or there is no calibration file provided to it. I don't remember how the programs get the calibration information and how/where it saves it.

**Comment by cnatzke** [comment]
That's exactly the problem, there is no calibration applied to the Analysis tree. The program doesn't require a calibration file as an input so there must be something funny happening in the program itself.

**Comment by VinzenzBildstein** [comment]
I checked and the Converter class should create a calibration and write it to the fragment and analysis file. Could you maybe put some debugging statements in to see if that happens? You can put a ```TChannel::WriteCalFile();``` in the destructor (before it gets written to the root files), and also on line 396 after the ```TChannel::AddChannel(channel);``` line. That should tell you a) whether the calibration has been built before we close the files, and b) that the adding of the channel works. Alternatively you can add more couts printing which channel we get after line 345 (```channel = TChannel::GetChannel(address);```).
