### ISSUE TITLE
Fatal error: TGriffin.h: No such file or directory

### ISSUE THREAD

**Issue by smayotte** [GRIFFINCollaboration/NTuple2EventTree#28]
GRSISort Version: 4.0.0.3
ROOT Version: 6.26/00
OS: Manjaro 22.0.0

When I try to compile NTuple2EventTree by running make I get the following error:
```
g++ Converter.cc -c -I/home/sonja/Work/programs/ape/ape.20220314/External/root/6.26.00/include/root -I/home/sonja/Work/programs/CommandLineInterface -I. -pthread -std=c++14 -m64 -I/home/sonja/Work/programs/ape/ape.20220314/External/root/6.26.00/include/root -pedantic -Wall -Wno-long-long -g -O3 -I/home/sonja/Work/programs/GRSISort-4.0.0.3/include -o Converter.o
In file included from Converter.cc:1:
Converter.hh:15:10: fatal error: TGriffin.h: No such file or directory
   15 | #include "TGriffin.h"
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:67: Converter.o] Error 1
```
As far as I can see that file is not included in any iterations of v4 of GRSISort. It is however present in v3.
I tried including the missing files from v3 (TGriffin.h as well as TBgo.h, TSceptar.h, TPaces.h, etc. which are also missing), but then I just get errors later, since v3 and v4 are not really compatible.

Am I doing something wrong while trying to compile NTuple2EventTree?

**Comment by VinzenzBildstein** [comment]
I double checked this and for me the compile command has an  ```-I($GRSISYS)/GRSIData/include``` just before the ```-o Converter.o```. Did you install GRSIData? And what does the makefile you have look like? Especially line 34 should be 
```
CXXFLAGS	   = $(ROOTFLAGS) -pedantic -Wall -Wno-long-long -g -O3 $(shell $(GRSI_CONFIG) --cflags --GRSIData-cflags)
```
So check what the result of running ```gris-config --cflags --GRSIData-cflags``` on the command line is. This should have the ```-I($GRSISYS)/GRSIData/include``` included.

**Comment by smayotte** [comment]
Thank you so much for the help! I did not have GRSIData installed because I did not know I needed it, but now everything works very nicely!
The older version of the code that we were using still had GRSISort and GRSIData combined. Maybe it could be helpful to mention the necessity of GRSIData for NTuple2EventTree in its README as well. I did find mention of that change in the Release notes, but its easy to miss if you're just checking out the main branch.

As a side note: I had some trouble with installation of GRSISort/GRSIData/NTuple2EventTree beyond this, because I was trying to install the newest Release versions of all 3 (for stability reasons) instead of the main branch and from the error messages I got I believe those Release versions are not compatible with each other (GRSISort 4.0.0.3 being much newer than GRSIData and NTuple2EventTree)

**Comment by VinzenzBildstein** [comment]
Oh yeah, the releases might not be aligned with each other. This is something we should correct. If you want the most recent version you should just pull the latest commit instead of using the releases. Those are done by hand and might not line up (as you just discovered).

**Comment by VinzenzBildstein** [comment]
And I've updated the README to include GRSIData (I thought the "properly set up" would include that, but now we also have the link in there).
