### ISSUE TITLE
fatal error: TRunInfo.h: No such file or directory

### ISSUE THREAD

**Issue by hrobertson2** [GRIFFINCollaboration/NTuple2EventTree#30]
Hello!  

I am having some issues installing NTuple2EventTree.  When I run make, I get the error that TRunInfo.h can't be found.  I'm using GRSISort version 4.0.0.2 and I do have GRSIData installed.

I have CommandLineInterface installed in my home directory and have added all the library paths to my bashrc, but am still running into this error.

Thank you!

**Comment by VinzenzBildstein** [comment]
What output do you get when you run ```grsi-config --cflags --GRSIData-cflags``` in the NTuple2EventTree directory?

**Comment by hrobertson2** [comment]
Running that line gives:

Unknown argument "--GRSIData-cflags"!
Usage: grsi-config [--version] [--incdir] [--cflags] [--libs] [--all-libs] [--<detector specific library>-libs] [--help]

**Comment by VinzenzBildstein** [comment]
Hmm, that sounds like the GRSISort version you are using is a bit old? Not sure if that's the issue, but that command is used in the current makefile of NTuple2EventTree, so the error could cause it to use the wrong compiler options. Can you check your makefile and see what it uses? Also, what is the exact output when you call make, i.e. what are the exact compiler commands that fail.

**Comment by hrobertson2** [comment]
I tried manually adding the cflags from my GRSIData makefile  (`-g -std=c++11 -O3 -Wall -Wextra -pedantic -Wno-unknown-pragmas -Wno-unused-function -Wshadow`)  but wound up getting similar errors.

The output of make is:

`Unknown argument "--GRSIData-cflags"!`
`Usage: grsi-config [--version] [--incdir] [--cflags] [--libs] [--all-libs] [--<detector specific library>-libs] [--help]
g++ Converter.cc -c -I/opt/root_v6.10.04/include -I/home/hrobertson2/packages/CommandLineInterface/CommandLineInterface -I. -pthread -std=c++11 -m64 -I/opt/root_v6.10.04/include -pedantic -Wall -Wno-long-long -g -O3  -o Converter.o
Unknown argument "--GRSIData-cflags"!`
`Usage: grsi-config [--version] [--incdir] [--cflags] [--libs] [--all-libs] [--<detector specific library>-libs] [--help]
In file included from Converter.cc:1:0:`
`Converter.hh:12:22: fatal error: TRunInfo.h: No such file or directory`
` #include "TRunInfo.h"`
`                      ^`
`compilation terminated.`
`make: *** [Converter.o] Error 1
`

**Comment by VinzenzBildstein** [comment]
I checked, and the ```--GRSIData-cflags``` option was added to grsiconfig three years ago, so GRSISort v4.0.2 which is four years old is too old to have this. So what you can do if you don't want to update GRSISort is to change the makefile, and remove the ```--GRSIData-cflags``` and instead add ```-I$(GRSISYS)/GRSIData/include``` (outside the call to gris-config).

**Comment by hrobertson2** [comment]
Is this what you mean by outside the call to grsi-config? 
`CXXFLAGS	= $(ROOTFLAGS) -pedantic -Wall -Wno-long-long -g -O3 -I$(GRSISYS)/GRSIData/include $(shell $(GRSI_CONFIG) --cflags)`

That seemed to fix the error of unknown arguments, but now I am having another similar error in which it can't find Utilities.hh

`g++ Converter.cc -c -I/opt/root_v6.10.04/include -I/home/hrobertson2/packages/CommandLineInterface/CommandLineInterface -I. -pthread -std=c++11 -m64 -I/opt/root_v6.10.04/include -pedantic -Wall -Wno-long-long -g -O3 -I/home/hrobertson2/packages/GRSISort/GRSIData/include -std=c++0x -I/home/hrobertson2/packages/GRSISort/include -o Converter.o`
`Converter.cc:10:24: fatal error: Utilities.hh: No such file or directory`
` #include "Utilities.hh"`
`                        ^
`

Could this also be something that is just not included in my version of GRSISort?

**Comment by hrobertson2** [comment]
The issue is fixed!  I had moved moved the location of CommandLineInterface and forgot to change it in the makefile. All is working now.  

Thank you so much!
