### ISSUE TITLE
Smearing for Sceptar

### ISSUE THREAD

**Issue by hrobertson2** [GRIFFINCollaboration/NTuple2EventTree#31]
Hello!

I am trying to apply some smearing to a Sceptar simulation, but it seems like in the Setting.cc file all the values being passed for Sceptar are 0.  Have we ever applied any smearing to Sceptar in the past and would these values possibly be stored somewhere?

Thank you!

Heather

**Comment by VinzenzBildstein** [comment]
The values in Settings.cc are only the default values. You can always change them in the settings file. That the default values for SCEPTAR are zero probably means that smearing hasn't been applied to SCEPTAR in the past (i.e. when Evan was working on this), but it doesn't mean you can use your own settings.
There's no need to change any of the values in Settings.cc, they are always overwritten by what you provide in the settings file itself.
