### ISSUE TITLE
No TBgo.h file in current GRSISort/include/

### ISSUE THREAD

**Issue by scshadrick** [GRIFFINCollaboration/NTuple2EventTree#5]
![notbgo](https://user-images.githubusercontent.com/20971746/31024587-c3de3f70-a4fc-11e7-92f7-60c30a8ffb9d.png)

**Comment by VinzenzBildstein** [comment]
The pull request which added these files to GRSISort hadn't been merged yet. It is now, so pulling the newest version of GRSISort should fix this.

**Comment by scshadrick** [comment]
![undefinedtbgo](https://user-images.githubusercontent.com/20971746/31024935-e5ed9de4-a4fd-11e7-9a40-06423746155a.png)

**Comment by VinzenzBildstein** [comment]
This not really a NTuple2EventTree issue anymore, but a GRSISort issue. Anyway, the newest pull request of GRSISort should fix this issue.

**Comment by scshadrick** [comment]
The latest pull of GRSISort is working fine now.  However, there are still some undefined references during making of NTuple2EventTree.  I have sourced the shell script for GRSISort inline and in bashrc, and the other files are in the right place according to the installation guide. This was the make output:

steven@work:~/NTuple2EventTree$ make -j4
g++ Converter.cc -c -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -o Converter.o
g++ Settings.cc -c -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -o Settings.o
g++ NTuple2EventTree.cc -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC Converter.o Settings.o NTuple2EventTreeDictionary.o -L/home/steven/lib -Wl,-rpath,/opt/gcc/lib64 -L/home/steven/root_install/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic -lCommandLineInterface -lUtilities -L/home/steven/GRSISort/lib -lTGRSIDetector -lTDetector -lTGRSIFormat -lTNucleus -lTKinematics -lTSRIM -lTBetaDecay -lTGRSIFit -lTCal -lGROOT -lTReaction -lTAngularCorrelation -lTFipps -lTTigress -lTGriffin -lTBgo -lTSharc -lTTriFoil -lTSceptar -lTPaces -lTDescant -lTTip -lTCSM -lTS3 -lTSiLi -lTRF -lTPulseAnalyzer -lTTAC -lTLaBr -lTZeroDegree -lTMidas -lTDataParser -lTGRSIint -lTLoops -lTHistogramming -lMakeAnalysisHistograms -lMakeGriffinFragmentHistograms -lMakeTigressHistograms -lXMLParser -lXMLIO -lX11 -lXpm -lProof -lGuiHtml -lMinuit -lPyROOT -lSpectrum -lMathMore -o NTuple2EventTree
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `AddFileToGUI(TFile*)'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `Version()'
/home/steven/GRSISort/lib/libTTriFoil.so: undefined reference to `TDetector::~TDetector()'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `typeinfo for TGRSIDetectorHit'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetSegment() const'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::SetHitBit(TGRSIDetectorHit::EBitFlag, bool) const'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `GValue::ReadValFile(char const*, char const*)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::~TGRSIDetectorHit()'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `TLstFile::TLstFile(char const*, TLstFile::EOpenType)'
/home/steven/GRSISort/lib/libTHistogramming.so: undefined reference to `vtable for GH1D'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `TMidasFile::TMidasFile(char const*, TMidasFile::EOpenType)'
/home/steven/GRSISort/lib/libTDescant.so: undefined reference to `GValue::Value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::Clear(char const*)'
/home/steven/GRSISort/lib/libTGriffin.so: undefined reference to `TGRSIDetectorHit::fPPG'
/home/steven/GRSISort/lib/libTPulseAnalyzer.so: undefined reference to `TGRSIFunctions::CsIFitFunction(double*, double*)'
/home/steven/GRSISort/lib/libTFipps.so: undefined reference to `typeinfo for TGRSIDetector'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::TGRSIDetectorHit(TGRSIDetectorHit const&, bool)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `typeinfo for TRawFile'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::ReadDoubleArray(TXMLNode*)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TMidasEvent::TMidasEvent()'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `StartGUI()'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::Copy(TObject&, bool) const'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::FindPath(char const*, TXMLNode*)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `GValue::fValueVector[abi:cxx11]'
/home/steven/GRSISort/lib/libTTigress.so: undefined reference to `TGRSIDetectorHit::~TGRSIDetectorHit()'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::ReadStringArray[abi:cxx11](TXMLNode*)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetCharge() const'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TLstEvent::Class()'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::TXMLOdb(char*, int)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDataParser::~TDataParser()'
/home/steven/GRSISort/lib/libTTriFoil.so: undefined reference to `TDetector::TDetector()'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::ReadIntArray(TXMLNode*)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetArrayNumber() const'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDetector::Class()'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetEnergy(char const*) const'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetName() const'
/home/steven/GRSISort/lib/libTFipps.so: undefined reference to `TGRSIDetector::Clear(char const*)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::Copy(TObject&) const'
/home/steven/GRSISort/lib/libTTriFoil.so: undefined reference to `TDetector::Copy(TObject&) const'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `typeinfo for TMidasFile'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TXMLOdb::GetNodeName(TXMLNode*)'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `GRootGuiFactory::GRootGuiFactory(char const*, char const*)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::TGRSIDetectorHit(int const&)'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetCrystal() const'
/home/steven/GRSISort/lib/libTTriFoil.so: undefined reference to `TDetector::Clear(char const*)'
/home/steven/GRSISort/lib/libTTigress.so: undefined reference to `TGRSIDetectorHit::TGRSIDetectorHit(TGRSIDetectorHit const&, bool)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDataParser::ClearQueue()'
/home/steven/GRSISort/lib/libTFipps.so: undefined reference to `TGRSIDetector::~TGRSIDetector()'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `ttree_fill_mutex'
/home/steven/GRSISort/lib/libTFipps.so: undefined reference to `TGRSIDetector::Copy(TObject&) const'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetTime(unsigned int const&, char const*) const'
/home/steven/GRSISort/lib/libTDescant.so: undefined reference to `GValue::FindValue(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDataParser::TDataParser()'
/home/steven/GRSISort/lib/libTFipps.so: undefined reference to `TGRSIDetector::TGRSIDetector()'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDataParser::SetFinished()'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetDetector() const'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::CopyWave(TObject&) const'
/home/steven/GRSISort/lib/libTTriFoil.so: undefined reference to `typeinfo for TDetector'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `gAnalysis'
/home/steven/GRSISort/lib/libTTigress.so: undefined reference to `TGRSIDetectorHit::TGRSIDetectorHit(int const&)'
/home/steven/GRSISort/lib/libTHistogramming.so: undefined reference to `GH2D::GH2D(char const*, char const*, int, double, double, int, double, double)'
/home/steven/GRSISort/lib/libTGRSIint.so: undefined reference to `gFragment'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TMidasEvent::GetTimeStamp() const'
/home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to `TGRSIDetectorHit::GetTimeStamp(char const*) const'
/home/steven/GRSISort/lib/libTLoops.so: undefined reference to `TDataParser::OutputQueueStatus[abi:cxx11]()'
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'NTuple2EventTree' failed
make: *** [NTuple2EventTree] Error 1
rm Settings.o Converter.o

**Comment by VinzenzBildstein** [comment]
what is the output of ```nm /home/steven/GRSISort/lib/libTGROOT.so | grep Version```, of ```nm /home/steven/GRSISort/lib/lib*.so | grep Version | grep -v VersionCheck```, and of ```grep _Z7Versionv /home/steven/GRSISort/lib/lib*.so```?

**Comment by scshadrick** [comment]
![outputvinzenz](https://user-images.githubusercontent.com/20971746/31029995-fb98da6a-a510-11e7-9711-61a45001e2c5.png)

**Comment by VinzenzBildstein** [comment]
That matches what I see, so Version() is defined in libGROOT.so, which the program is being linked against (first command should have been libGROOT.so, not libTGROOT.so). So I don't understand where the error comes from. You could try executing the link command by hand (not via the makefile) and re-ordering the libraries in case their order plays a role (I think this differs between OSes).

**Comment by scshadrick** [comment]
When the $(LOADLIBES) and $(LDLIBS) on line 63 of the makefile are swapped, we only get 1 undefined reference to a symbol.

steven@work:~/NTuple2EventTree$ make
g++ Converter.cc -c -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -o Converter.o
g++ Settings.cc -c -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -o Settings.o
g++ NTuple2EventTree.cc -std=gnu++0x -pedantic -Wall -Wno-long-long -g -O3 -std=c++0x -I/home/steven/GRSISort/include -I/home/steven/root_install/include -I/home/steven/CommandLineInterface -I. -fPIC -L/home/steven/lib -Wl,-rpath,/opt/gcc/lib64 -L/home/steven/root_install/lib -lCore -lImt -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lTreePlayer -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -lMultiProc -pthread -lm -ldl -rdynamic -lCommandLineInterface -lUtilities -L/home/steven/GRSISort/lib -lTGRSIDetector -lTDetector -lTGRSIFormat -lTNucleus -lTKinematics -lTSRIM -lTBetaDecay -lTGRSIFit -lTCal -lGROOT -lTReaction -lTAngularCorrelation -lTFipps -lTTigress -lTGriffin -lTBgo -lTSharc -lTTriFoil -lTSceptar -lTPaces -lTDescant -lTTip -lTCSM -lTS3 -lTSiLi -lTRF -lTPulseAnalyzer -lTTAC -lTLaBr -lTZeroDegree -lTMidas -lTDataParser -lTGRSIint -lTLoops -lTHistogramming -lMakeAnalysisHistograms -lMakeGriffinFragmentHistograms -lMakeTigressHistograms -lXMLParser -lXMLIO -lX11 -lXpm -lProof -lGuiHtml -lMinuit -lPyROOT -lSpectrum -lMathMore Converter.o Settings.o NTuple2EventTreeDictionary.o -o NTuple2EventTree
/usr/bin/ld: /home/steven/GRSISort/lib/libTGRSIFormat.so: undefined reference to symbol '_ZN5TFileC1EPKcS1_S1_i'
/home/steven/root_install/lib/libRIO.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:63: recipe for target 'NTuple2EventTree' failed
make: *** [NTuple2EventTree] Error 1
rm Settings.o Converter.o

**Comment by VinzenzBildstein** [comment]
Anything to do with TFile should be defined in the root libraries. So try moving the root libraries in the last step to a different place.

**Comment by VinzenzBildstein** [comment]
You might also want to try adding a --no-as-needed to the last command.

**Comment by scshadrick** [comment]
Alright, I found a dirty way to compile it, but it seems to be functional.  The dependencies are in a strange order for the compiler it seems, but I set lines 54-64 to:

# -------------------- pattern rules --------------------
# this rule sets the name of the .cc file at the beginning of the line (easier to find)

%.o: %.cc %.hh
	$(CXX) $< -c $(CPPFLAGS) $(CXXFLAGS) -lstd $(LDLIBS) -o $@

# -------------------- default rule for executables --------------------

%: %.cc $(LOADLIBES)
	$(CXX) $< $(CXXFLAGS) $(CPPFLAGS) $(LDLIBS) $(LOADLIBES) -lGROOT $(LDLIBS) -o $@

**Comment by VinzenzBildstein** [comment]
This seems really weird, not sure why your compiler needs -lstd and the LDLIBS to compile object files, and the GROOT library should already be included in the LDLIBS (which are used twice for the executables), but at least you got it working.
Could you please specify which compiler and which operating system you are using?

**Comment by scshadrick** [comment]
I'm on Ubuntu 16.04 LTE with version 5.4 of gcc(++) compiler.  I made sure my stuff was (mostly) up to date and I had what I needed for the install.

**Comment by VinzenzBildstein** [comment]
Okay, thanks. This information might help other people that use newer compilers. I couldn't reproduce the problem with CentOS 6.9 or 7.4 using gcc 4.9.3.
